//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhpEntityGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 12pt, style=Bold")]
        public global::System.Drawing.Font s_Font {
            get {
                return ((global::System.Drawing.Font)(this["s_Font"]));
            }
            set {
                this["s_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color s_BGC {
            get {
                return ((global::System.Drawing.Color)(this["s_BGC"]));
            }
            set {
                this["s_BGC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_FGC {
            get {
                return ((global::System.Drawing.Color)(this["s_FGC"]));
            }
            set {
                this["s_FGC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t/**\r\n\t * @Column({col_def})\r\n\t */\r\n\tprotected ${name};\r\n\r\n")]
        public string s_FieldTemplate {
            get {
                return ((string)(this["s_FieldTemplate"]));
            }
            set {
                this["s_FieldTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t/**\r\n\t * Get the value of {name}\r\n\t */\r\n\tpublic function get{proper_name}()\r\n\t{\r" +
            "\n\t\treturn $this->{name};\r\n\t}\r\n\r\n")]
        public string s_GetterTemplate {
            get {
                return ((string)(this["s_GetterTemplate"]));
            }
            set {
                this["s_GetterTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t/**\r\n\t * Set the value of {name}\r\n\t * \r\n\t * @return self\r\n\t */\r\n\tpublic function" +
            " set{proper_name}(${name})\r\n\t{\r\n\t\t$this->updateProperty(\'{name}\', ${name});\r\n\t\t\r" +
            "\n\t\treturn $this;\r\n\t}\r\n\r\n")]
        public string s_SetterTemplate {
            get {
                return ((string)(this["s_SetterTemplate"]));
            }
            set {
                this["s_SetterTemplate"] = value;
            }
        }
    }
}
